/*
 * faasnap
 *
 * FaaSnap API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Invocation struct {
	FuncName       string  `json:"func_name"`
	VmId           string  `json:"vmId,omitempty"`
	SsId           string  `json:"ssId,omitempty"`
	Params         string  `json:"params,omitempty"`
	Mincore        int32   `json:"mincore,omitempty"`
	MincoreSize    int32   `json:"mincore_size,omitempty"`
	LoadMincore    []int32 `json:"loadMincore,omitempty"`
	UseMemFile     bool    `json:"use_mem_file,omitempty"`
	OverlayRegions bool    `json:"overlay_regions,omitempty"`
	UseWsFile      bool    `json:"use_ws_file,omitempty"`
	VmmLoadWs      bool    `json:"vmm_load_ws,omitempty"`
	EnableReap     bool    `json:"enableReap,omitempty"`
	WsFileDirectIo bool    `json:"wsFileDirectIo,omitempty"`
	WsSingleRead   bool    `json:"wsSingleRead,omitempty"`
	Namespace      string  `json:"namespace,omitempty"`
}
