/*
 * faasnap
 *
 * FaaSnap API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VmmsBody struct {
	Namespace  string `json:"namespace,omitempty"`
	EnableReap bool   `json:"enableReap,omitempty"`
}
