/*
 * api
 *
 * FaaSnap API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SsIdMincoreBody1 struct {
	FromRecordsSize   int32   `json:"from_records_size,omitempty"`
	TrimRegions       bool    `json:"trim_regions,omitempty"`
	ToWsFile          string  `json:"to_ws_file,omitempty"`
	InactiveWs        bool    `json:"inactive_ws,omitempty"`
	ZeroWs            bool    `json:"zero_ws,omitempty"`
	SizeThreshold     int32   `json:"size_threshold,omitempty"`
	IntervalThreshold int32   `json:"interval_threshold,omitempty"`
	MincoreCache      []int32 `json:"mincore_cache,omitempty"`
	DropWsCache       bool    `json:"drop_ws_cache,omitempty"`
}
