/*
 * api
 *
 * FaaSnap API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Function struct {
	FuncName string `json:"func_name"`
	Image    string `json:"image,omitempty"`
	Kernel   string `json:"kernel,omitempty"`
	Vcpu     int32  `json:"vcpu,omitempty"`
	MemSize  int32  `json:"mem_size,omitempty"`
}
