/*
 * api
 *
 * FaaSnap API
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SnapshotsSsIdBody struct {
	DigHole   bool `json:"dig_hole,omitempty"`
	LoadCache bool `json:"load_cache,omitempty"`
	DropCache bool `json:"drop_cache,omitempty"`
}
